/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.debezium.message;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RemoveOperation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RemoveOperation\",\"namespace\":\"org.debezium.message\",\"fields\":[{\"name\":\"path\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence path;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public RemoveOperation() {}

  /**
   * All-args constructor.
   */
  public RemoveOperation(java.lang.CharSequence path) {
    this.path = path;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return path;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: path = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'path' field.
   */
  public java.lang.CharSequence getPath() {
    return path;
  }

  /**
   * Sets the value of the 'path' field.
   * @param value the value to set.
   */
  public void setPath(java.lang.CharSequence value) {
    this.path = value;
  }

  /** Creates a new RemoveOperation RecordBuilder */
  public static org.debezium.message.RemoveOperation.Builder newBuilder() {
    return new org.debezium.message.RemoveOperation.Builder();
  }
  
  /** Creates a new RemoveOperation RecordBuilder by copying an existing Builder */
  public static org.debezium.message.RemoveOperation.Builder newBuilder(org.debezium.message.RemoveOperation.Builder other) {
    return new org.debezium.message.RemoveOperation.Builder(other);
  }
  
  /** Creates a new RemoveOperation RecordBuilder by copying an existing RemoveOperation instance */
  public static org.debezium.message.RemoveOperation.Builder newBuilder(org.debezium.message.RemoveOperation other) {
    return new org.debezium.message.RemoveOperation.Builder(other);
  }
  
  /**
   * RecordBuilder for RemoveOperation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RemoveOperation>
    implements org.apache.avro.data.RecordBuilder<RemoveOperation> {

    private java.lang.CharSequence path;

    /** Creates a new Builder */
    private Builder() {
      super(org.debezium.message.RemoveOperation.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.debezium.message.RemoveOperation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.path)) {
        this.path = data().deepCopy(fields()[0].schema(), other.path);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing RemoveOperation instance */
    private Builder(org.debezium.message.RemoveOperation other) {
            super(org.debezium.message.RemoveOperation.SCHEMA$);
      if (isValidValue(fields()[0], other.path)) {
        this.path = data().deepCopy(fields()[0].schema(), other.path);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'path' field */
    public java.lang.CharSequence getPath() {
      return path;
    }
    
    /** Sets the value of the 'path' field */
    public org.debezium.message.RemoveOperation.Builder setPath(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.path = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'path' field has been set */
    public boolean hasPath() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'path' field */
    public org.debezium.message.RemoveOperation.Builder clearPath() {
      path = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public RemoveOperation build() {
      try {
        RemoveOperation record = new RemoveOperation();
        record.path = fieldSetFlags()[0] ? this.path : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
