FROM debezium-samza

MAINTAINER rhauch

#
# Add this service's files to the Debezium service installation
#
ADD debezium-service-contents.tar.gz $DEBEZIUM_HOME

#
# Set up the ENV for the Kakfa and ZK host and ports
#

#
# Set up the data volume ?
#

#
# Start the service
#
